CREATE TABLE POSTS (
  id INT IDENTITY,
  title CHAR(30),
  content CHAR(300),
  smallimg CHAR(20),
  bigimg CHAR(20),
  rating INT DEFAULT 3,
  istopnews BOOLEAN DEFAULT FALSE,
  userid INT NOT NULL,
  date DATE DEFAULT CURRENT_DATE,
  time TIME DEFAULT CURRENT_TIME
);
CREATE TABLE USERS (
  id INT IDENTITY,
  firstname CHAR(20),
  lastname CHAR(20),
  email CHAR(20) NOT NULL,
  password CHAR(30) NOT NULL,
  roleid INT NOT NULL
);
CREATE TABLE POSTS_TAGS (
  id INT IDENTITY,
  postid INT NOT NULL,
  tagid INT NOT NULL
);
CREATE TABLE REF_ROLES (
  id INT IDENTITY,
  name CHAR(20) NOT NULL
);
CREATE TABLE REF_TAGS (
  id INT IDENTITY,
  name CHAR(30) NOT NULL
);

INSERT INTO REF_ROLES(name) VALUES ('admin');
INSERT INTO REF_ROLES(name) VALUES ('writer');
INSERT INTO REF_ROLES(name) VALUES ('author');
INSERT INTO REF_ROLES(name) VALUES ('corrector');

INSERT INTO REF_TAGS(name) VALUES ('music');
INSERT INTO REF_TAGS(name) VALUES ('art');
INSERT INTO REF_TAGS(name) VALUES ('sport');